### ISSUE TITLE
Propagate GH assignees to Jira ticket

### ISSUE THREAD

**Issue by eriknelson** [konveyor/github-actions#11]
We'd like the bot to propagate the GH issue assignee to the Jira ticket. Probably
could use some kind of a yaml mapping and have the team PR in their own mapping:

mapping.yml

```yaml
mapping:
  ernelson:
    github: eriknelson
    jira: ernelson@redhat.com
  dzager:
    # etc...
```
